name: 'Firebase App Distribution'
description: 'GitHub Action that uploads symbols to Firebase Crashlytics'
author: 'Maxim Matveev'
inputs:
  appId:
    description: 'App id can be found on the General Settings page'
    required: true
  token:
    description: 'Upload token - see Firebase CLI Reference'
    required: false
  serviceCredentialsFile:
    description: 'Service credentials file'
    required: false
  serviceCredentialsFileContent:
    description: 'Content of service credentials file'
    required: false
  file:
    description: 'Zipped symbols'
    required: true
branding:
  color: 'orange'
  icon: 'send'
runs:
  using: 'docker'
  image: 'Dockerfile'
